In [0]:
import numpy as np

In [0]:
x = np.array(([2, 9], [1, 5], [3, 6]), dtype = float)
y = np.array(([92], [86], [89]), dtype = float)
xPredicted = np.array(([4,8]), dtype=float)

In [0]:
x = x / np.max(x, axis = 0)
y = y/100
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)

In [0]:
class Neural_Network(object):
 
  def __init__(self):
    self.inputsize = 2
    self.outputsize = 1
    self.hiddensize = 3
    self.W1 = np.random.randn(self.inputsize, self.hiddensize)
    self.W2 = np.random.randn(self.hiddensize, self.outputsize)
    
  def forward(self, x):
    self.z = np.dot(x,self.W1)
    self.z2 = self.sigmoid(self.z)
    self.z3 = np.dot(self.z2, self.W2)
    o = self.sigmoid(self.z3)
    return o
  
  def sigmoidPrime(self, s):
  #derivative of sigmoid
    return s * (1 - s)
  
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))
  
  def backward(self, X, y, o):
  # backward propagate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
  
  def train(self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

  def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")

  def predict(self):
    print "Predicted data based on trained weights: ";
    print "Input (scaled): \n" + str(xPredicted);
    print "Output: \n" + str(self.forward(xPredicted));

In [19]:
NN = Neural_Network()
# o = NN.forward(x)
# print "Predicted Output: \n" + str(o)
# print "Actual Output: \n" + str(y)
for i in xrange(1000): # trains the NN 1,000 times
  print "# " + str(i) + "\n"
  print "Input (scaled): \n" + str(x)
  print "Actual Output: \n" + str(y)
  print "Predicted Output: \n" + str(NN.forward(x))
  print "Loss: \n" + str(np.mean(np.square(y - NN.forward(x)))) # mean sum squared loss
  print "\n"
  NN.train(x, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.17368527]
 [0.18000672]
 [0.20597867]]
Loss: 
0.49575390318514256


# 1

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.22830837]
 [0.22923122]
 [0.25743507]]
Loss: 
0.42548164988787246


# 2

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.29389487]
 [0.28885128]
 [0.31552975]]
Loss: 
0.349411517714073


# 3

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.36526079]
 [0.35506501]
 [0.37564591]]
Loss: 
0.2757516889566386


# 4

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.       